+@\0&ru0 0

# Assuming the input provided travels clockwise,
# reverse so that it becomes counterclockwise.
⇌⊜(⍜°{⊙⊙∘}⊓⊓⊢⋕(↙6↘2)⊜□≠@ .)≠@\n.

# Wrapping Windows
WW ← ≡↙:≡↻⇡⊃⧻¤:

PartOne ← ≡↙2

PartTwo ← ≡(
  ⊐⊃(↙5|-@0⊢⇌)⊢⇌
  ⊐⊗:⊂+@0⇡10+@a⇡6
  /+×ⁿ:16⇌⇡5
  ⊟∩□⊡:"RDLU":
)

(PartOne|PartTwo) -1⋕⊡1&args

\+≡(×-1⁅÷2⊗:"LDUR"°{⊙∘}).
∩▽,:↻⊙(◿2⇡⧻,)∊:"UD"⊢⊢,↻¯2WW4
⊃(
  +=@U⊐≡⊢:≡⊡1
| ±≡(⊏0_2)≡≡/-≡◫2
  ⍜×(↥0)≡(-1×2⊗:"DU"⊢),
  ≡(/+×1_¯1)
)
⊙⊙≡(×-1×2⊗:"DU"°{⊙∘})
/+×⊙+
